[package]
name = "aptos-streaming-partitioner"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
aptos-block-executor = { workspace = true }
aptos-block-partitioner = { workspace = true }
aptos-graphs = { workspace = true }
aptos-transaction-orderer = { workspace = true }
aptos-types = { workspace = true }
itertools = { workspace = true }
namable_closures = { workspace = true }
nonmax = { workspace = true }
rand = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }

[features]
# Enables the metis partitioner, which requires metis to be installed on the system.
metis-partitioner = ["aptos-graphs/metis-partitioner"]
